import type { RelocationMissionFixture } from "./types";

export const relocationMission: RelocationMissionFixture = {
  disclosure:
    "Representative fixture data for interface review. No live websites, integrations, bookings, purchases, messages, or provider actions are shown.",
  prompt:
    "I am moving from Phoenix to San Francisco in 10 days for a new job. Keep planned move-in costs under $8,000, work around my calendar, and prioritize a bright apartment within 30 minutes of the office with no ground-floor units. I am bringing my desk but almost no other furniture. Prepare everything you can, but do not book, buy, sign, or send anything without my approval.",
  mandate: {
    goal: "Arrive ready for work in San Francisco within 10 days",
    constraints: [
      "Planned move-in costs stay under $8,000",
      "Bright apartment, above ground floor, within 30 minutes of the office",
      "Calendar-aware travel and delivery windows",
      "No booking, buying, signing, or sending without approval",
    ],
    branches: [
      "Housing",
      "Travel",
      "Moving",
      "Home",
      "Utilities",
      "Admin",
      "First Week",
    ],
    approvalBoundary:
      "Cardea may research, compare, and prepare drafts. You approve every consequential action.",
  },
  wallet: [
    {
      id: "personal",
      name: "Personal",
      detail: "Preferences and authority",
      accent: "coral",
      symbol: "P",
    },
    {
      id: "work",
      name: "Work",
      detail: "Office and calendar context",
      accent: "blue",
      symbol: "W",
    },
    {
      id: "home",
      name: "Home",
      detail: "Space and delivery needs",
      accent: "sage",
      symbol: "H",
    },
    {
      id: "travel",
      name: "Travel",
      detail: "Route preferences",
      accent: "ink",
      symbol: "T",
    },
  ],
  nodes: [
    {
      id: "lyra",
      codename: "Lyra",
      role: "Housing",
      task: "Compare two viable homes",
      progress: 64,
      status: "active",
      commentary: "Two representative candidates meet the recorded constraints.",
      previewTitle: "Mission fixture · apartment comparison",
      previewDetail: "Bright · upper floor · 24 min to office",
      x: 13,
      y: 14,
    },
    {
      id: "hermes",
      codename: "Hermes",
      role: "Travel",
      task: "Hold arrival windows",
      progress: 72,
      status: "active",
      commentary: "Arrival windows remain provisional until housing is chosen.",
      previewTitle: "Mission fixture · route options",
      previewDetail: "PHX → SFO · 3 workable windows",
      x: 39,
      y: 28,
    },
    {
      id: "atlas",
      codename: "Atlas",
      role: "Moving",
      task: "Compare mover estimates",
      progress: 48,
      status: "active",
      commentary: "Two estimates fit the budget, pending the final address.",
      previewTitle: "Mission fixture · mover comparison",
      previewDetail: "2 estimates · no action taken",
      x: 67,
      y: 14,
    },
    {
      id: "hestia",
      codename: "Hestia",
      role: "Home",
      task: "Stage essential furniture",
      progress: 36,
      status: "active",
      commentary: "Delivery plans follow the apartment handoff window.",
      previewTitle: "Mission fixture · essentials list",
      previewDetail: "Bed · lighting · kitchen basics",
      x: 5,
      y: 52,
    },
    {
      id: "electra",
      codename: "Electra",
      role: "Utilities",
      task: "Prepare service starts",
      progress: 41,
      status: "active",
      commentary: "Draft start dates are linked to the selected address.",
      previewTitle: "Mission fixture · service checklist",
      previewDetail: "Power · internet · water",
      x: 31,
      y: 54,
    },
    {
      id: "themis",
      codename: "Themis",
      role: "Admin",
      task: "Prepare change-of-address list",
      progress: 58,
      status: "active",
      commentary: "A reviewable checklist is ready, nothing has been sent.",
      previewTitle: "Mission fixture · admin checklist",
      previewDetail: "8 drafts · approval required",
      x: 57,
      y: 52,
    },
    {
      id: "aurora",
      codename: "Aurora",
      role: "First Week",
      task: "Shape the first-week plan",
      progress: 29,
      status: "active",
      commentary: "The plan is fitting orientation around the move.",
      previewTitle: "Mission fixture · first-week plan",
      previewDetail: "Orientation · commute · essentials",
      x: 79,
      y: 46,
    },
  ],
  activity: [
    {
      id: "a1",
      time: "00:01",
      kind: "Plan",
      title: "Mandate split into seven coordinated branches",
      detail: "The fixture models housing as the dependency for travel, home, utilities, and budget updates.",
    },
    {
      id: "a2",
      time: "00:06",
      kind: "Actions",
      title: "Representative comparison prepared",
      detail: "Two housing candidates were added to the fixture preview. No external website was opened.",
    },
    {
      id: "a3",
      time: "00:09",
      kind: "Evidence",
      title: "Constraints checked against fixture attributes",
      detail: "Brightness, floor, commute, and budget fields are visible in the comparison.",
    },
    {
      id: "a4",
      time: "00:12",
      kind: "Errors",
      title: "Leading apartment marked unavailable in fixture",
      detail: "The dependency model preserves partial progress and exposes recovery controls.",
    },
    {
      id: "a5",
      time: "00:13",
      kind: "Decisions",
      title: "Dependent plans rerouted to the alternate address",
      detail: "Travel, delivery, utilities, and the planned budget update together.",
    },
    {
      id: "a6",
      time: "00:15",
      kind: "Approvals",
      title: "Apartment choice requires your judgment",
      detail: "The interface requests approval without booking, signing, buying, or sending anything.",
    },
  ],
  memories: [
    {
      id: "m1",
      text: "Natural light matters more than extra square footage.",
      source: "Explicit preference in this mission",
      influence: "Influenced Lyra · Housing ranking",
    },
    {
      id: "m2",
      text: "Keep the desk, buy only first-week essentials.",
      source: "Relocation mandate",
      influence: "Influenced Hestia · Home planning",
    },
  ],
};
